import type {
  Owner,
  Sector,
  RoutineTask,
  OKR,
  KR,
  Incident,
  Experiment,
  ScoreEntry,
  WeeklyCanvas,
} from '@/types';

const today = new Date().toISOString().split('T')[0];
const weekStart = new Date();
weekStart.setDate(weekStart.getDate() - weekStart.getDay());
const weekEnd = new Date(weekStart);
weekEnd.setDate(weekEnd.getDate() + 6);

export const generateSeedData = () => {
  const owners: Owner[] = [
    { id: 'owner-1', nome: 'Péricles', cargo: 'CEO', avatarColor: 'hsl(220, 70%, 50%)' },
    { id: 'owner-2', nome: 'Stella', cargo: 'CFO', avatarColor: 'hsl(280, 65%, 60%)' },
    { id: 'owner-3', nome: 'Walistter', cargo: 'CMO', avatarColor: 'hsl(142, 76%, 36%)' },
    { id: 'owner-4', nome: 'Elisangela', cargo: 'Marketing/Vendas/CRM', avatarColor: 'hsl(38, 92%, 50%)' },
  ];

  const sectors: Sector[] = [
    { id: 'sector-1', nome: 'Oferta & Preço', ownerId: 'owner-1' },
    { id: 'sector-2', nome: 'Tráfego Pago', ownerId: 'owner-3' },
    { id: 'sector-3', nome: 'Conversão (Site + Marketplace)', ownerId: 'owner-4' },
    { id: 'sector-4', nome: 'CRM & Remarketing', ownerId: 'owner-4' },
    { id: 'sector-5', nome: 'Criativos & Conteúdo', ownerId: 'owner-3' },
    { id: 'sector-6', nome: 'Operação (SLA/Expedição)', ownerId: 'owner-1' },
    { id: 'sector-7', nome: 'Financeiro & Controle', ownerId: 'owner-2' },
  ];

  const routineTasks: RoutineTask[] = [
    {
      id: 'task-1',
      sectorId: 'sector-1',
      nome: 'Definir Oferta do Dia',
      horario: '09:00',
      dod: 'Oferta definida com preço, margem e estoque validados',
      checklist: [
        { id: 'c1', text: 'Verificar estoque disponível', checked: false },
        { id: 'c2', text: 'Calcular margem mínima', checked: false },
        { id: 'c3', text: 'Definir desconto/bundle', checked: false },
      ],
      evidencia: '',
      prioridade: 'high',
      status: 'todo',
      recorrencia: true,
      diasSemana: [1, 2, 3, 4, 5],
      pontosOnDone: 10,
      pontosOnFail: -15,
      isCritical: false,
      date: today,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'task-2',
      sectorId: 'sector-3',
      nome: 'Publicar Oferta do Dia',
      horario: '10:00',
      dod: 'Oferta publicada em todos os canais (site, marketplaces, redes)',
      checklist: [
        { id: 'c1', text: 'Atualizar banner site', checked: false },
        { id: 'c2', text: 'Publicar no ML/Shopee/Magalu', checked: false },
        { id: 'c3', text: 'Postar nos Stories', checked: false },
      ],
      evidencia: '',
      prioridade: 'high',
      status: 'todo',
      recorrencia: true,
      diasSemana: [1, 2, 3, 4, 5],
      pontosOnDone: 10,
      pontosOnFail: -15,
      isCritical: false,
      date: today,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'task-3',
      sectorId: 'sector-2',
      nome: 'Hipótese do Teste do Dia',
      horario: '10:30',
      dod: 'Hipótese documentada com variável a testar e métrica de sucesso',
      checklist: [
        { id: 'c1', text: 'Definir hipótese clara', checked: false },
        { id: 'c2', text: 'Escolher variável de teste', checked: false },
        { id: 'c3', text: 'Definir métrica de sucesso', checked: false },
      ],
      evidencia: '',
      prioridade: 'normal',
      status: 'todo',
      recorrencia: true,
      diasSemana: [1, 2, 3, 4, 5],
      pontosOnDone: 5,
      pontosOnFail: -10,
      isCritical: false,
      date: today,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'task-4',
      sectorId: 'sector-2',
      nome: 'Subir Teste Novo',
      horario: '11:00',
      dod: 'Teste ativo no Ads Manager com criativo e copy definidos',
      checklist: [
        { id: 'c1', text: 'Criar variação no Ads', checked: false },
        { id: 'c2', text: 'Definir budget do teste', checked: false },
        { id: 'c3', text: 'Ativar campanha', checked: false },
      ],
      evidencia: '',
      prioridade: 'urgent',
      status: 'todo',
      recorrencia: true,
      diasSemana: [1, 2, 3, 4, 5],
      pontosOnDone: 15,
      pontosOnFail: -25,
      isCritical: true,
      date: today,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'task-5',
      sectorId: 'sector-3',
      nome: 'Auditoria 3 simulações mobile',
      horario: '12:00',
      dod: '3 simulações de compra mobile finalizadas sem erros',
      checklist: [
        { id: 'c1', text: 'Testar checkout mobile site', checked: false },
        { id: 'c2', text: 'Testar checkout ML', checked: false },
        { id: 'c3', text: 'Testar checkout Shopee', checked: false },
      ],
      evidencia: '',
      prioridade: 'high',
      status: 'todo',
      recorrencia: true,
      diasSemana: [1, 2, 3, 4, 5],
      pontosOnDone: 10,
      pontosOnFail: -15,
      isCritical: false,
      date: today,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'task-6',
      sectorId: 'sector-4',
      nome: 'Disparo CRM',
      horario: '13:00',
      dod: 'Campanha de CRM disparada para base segmentada',
      checklist: [
        { id: 'c1', text: 'Segmentar base', checked: false },
        { id: 'c2', text: 'Validar copy e links', checked: false },
        { id: 'c3', text: 'Disparar e monitorar entregas', checked: false },
      ],
      evidencia: '',
      prioridade: 'urgent',
      status: 'todo',
      recorrencia: true,
      diasSemana: [1, 2, 3, 4, 5],
      pontosOnDone: 15,
      pontosOnFail: -25,
      isCritical: true,
      date: today,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'task-7',
      sectorId: 'sector-5',
      nome: 'Publicar 3 criativos',
      horario: '14:00',
      dod: '3 criativos novos publicados nas redes/ads',
      checklist: [
        { id: 'c1', text: 'Revisar criativos com copy', checked: false },
        { id: 'c2', text: 'Publicar no feed/stories', checked: false },
        { id: 'c3', text: 'Adicionar ao Ads Manager', checked: false },
      ],
      evidencia: '',
      prioridade: 'high',
      status: 'todo',
      recorrencia: true,
      diasSemana: [1, 2, 3, 4, 5],
      pontosOnDone: 10,
      pontosOnFail: -15,
      isCritical: false,
      date: today,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'task-8',
      sectorId: 'sector-6',
      nome: 'Janela de corte/SLA/backlog',
      horario: '16:00',
      dod: 'Backlog zerado até horário de corte, SLA de expedição ok',
      checklist: [
        { id: 'c1', text: 'Verificar pedidos pendentes', checked: false },
        { id: 'c2', text: 'Confirmar expedição do dia', checked: false },
        { id: 'c3', text: 'Atualizar status no sistema', checked: false },
      ],
      evidencia: '',
      prioridade: 'high',
      status: 'todo',
      recorrencia: true,
      diasSemana: [1, 2, 3, 4, 5],
      pontosOnDone: 10,
      pontosOnFail: -15,
      isCritical: false,
      date: today,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'task-9',
      sectorId: 'sector-7',
      nome: 'Painel 5 números',
      horario: '18:00',
      dod: 'Painel atualizado com receita, pedidos, ticket, margem, gasto mídia',
      checklist: [
        { id: 'c1', text: 'Coletar receita do dia', checked: false },
        { id: 'c2', text: 'Calcular margem bruta', checked: false },
        { id: 'c3', text: 'Atualizar painel', checked: false },
      ],
      evidencia: '',
      prioridade: 'urgent',
      status: 'todo',
      recorrencia: true,
      diasSemana: [1, 2, 3, 4, 5],
      pontosOnDone: 20,
      pontosOnFail: -30,
      isCritical: true,
      date: today,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'task-10',
      sectorId: 'sector-1',
      nome: 'Ritual 3-3-3',
      horario: '18:15',
      dod: '3 vitórias, 3 aprendizados, 3 ações para amanhã documentados',
      checklist: [
        { id: 'c1', text: 'Listar 3 vitórias do dia', checked: false },
        { id: 'c2', text: 'Listar 3 aprendizados', checked: false },
        { id: 'c3', text: 'Definir 3 ações para amanhã', checked: false },
      ],
      evidencia: '',
      prioridade: 'urgent',
      status: 'todo',
      recorrencia: true,
      diasSemana: [1, 2, 3, 4, 5],
      pontosOnDone: 20,
      pontosOnFail: -30,
      isCritical: true,
      date: today,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ];

  const okrs: OKR[] = [
    // Oferta & Preço
    {
      id: 'okr-1',
      sectorId: 'sector-1',
      titulo: 'Maximizar margem com ofertas estratégicas',
      descricao: 'Criar ofertas que aumentem ticket médio mantendo margem saudável',
      ownerId: 'owner-1',
      status: 'doing',
      periodo: 'trimestre',
      semaforo: 'verde',
    },
    // Tráfego Pago
    {
      id: 'okr-2',
      sectorId: 'sector-2',
      titulo: 'Escalar tráfego qualificado com CPA controlado',
      descricao: 'Aumentar volume de tráfego mantendo CPA abaixo de R$25',
      ownerId: 'owner-3',
      status: 'doing',
      periodo: 'trimestre',
      semaforo: 'amarelo',
    },
    // Conversão
    {
      id: 'okr-3',
      sectorId: 'sector-3',
      titulo: 'Aumentar taxa de conversão do site',
      descricao: 'Otimizar jornada de compra para converter mais visitantes',
      ownerId: 'owner-4',
      status: 'doing',
      periodo: 'trimestre',
      semaforo: 'verde',
    },
  ];

  const krs: KR[] = [
    // OKR 1 - Oferta & Preço
    { id: 'kr-1', okrId: 'okr-1', nome: 'Ticket Médio', definicao: 'Valor médio por pedido', meta: 180, frequencia: 'diario', valorAtual: 165, semaforo: 'amarelo', fonte: 'ERP', evidencia: '', notes: '' },
    { id: 'kr-2', okrId: 'okr-1', nome: 'Margem Bruta', definicao: 'Margem sobre custo do produto', meta: 45, frequencia: 'diario', valorAtual: 42, semaforo: 'amarelo', fonte: 'ERP', evidencia: '', notes: '' },
    { id: 'kr-3', okrId: 'okr-1', nome: 'Ofertas ativas', definicao: 'Quantidade de ofertas ativas por dia', meta: 5, frequencia: 'diario', valorAtual: 4, semaforo: 'verde', fonte: 'Manual', evidencia: '', notes: '' },
    // OKR 2 - Tráfego Pago
    { id: 'kr-4', okrId: 'okr-2', nome: 'CPA', definicao: 'Custo por aquisição', meta: 25, frequencia: 'diario', valorAtual: 28, semaforo: 'vermelho', fonte: 'Ads Manager', evidencia: '', notes: '' },
    { id: 'kr-5', okrId: 'okr-2', nome: 'Sessões Ads', definicao: 'Sessões vindas de mídia paga', meta: 2000, frequencia: 'diario', valorAtual: 1850, semaforo: 'amarelo', fonte: 'GA4', evidencia: '', notes: '' },
    { id: 'kr-6', okrId: 'okr-2', nome: 'ROAS', definicao: 'Retorno sobre gasto com mídia', meta: 4, frequencia: 'diario', valorAtual: 3.2, semaforo: 'amarelo', fonte: 'Ads Manager', evidencia: '', notes: '' },
    // OKR 3 - Conversão
    { id: 'kr-7', okrId: 'okr-3', nome: 'Taxa de Conversão', definicao: 'Visitantes que compram', meta: 2.5, frequencia: 'diario', valorAtual: 2.1, semaforo: 'amarelo', fonte: 'GA4', evidencia: '', notes: '' },
    { id: 'kr-8', okrId: 'okr-3', nome: 'Add to Cart Rate', definicao: 'Visitantes que adicionam ao carrinho', meta: 8, frequencia: 'diario', valorAtual: 7.5, semaforo: 'verde', fonte: 'GA4', evidencia: '', notes: '' },
    { id: 'kr-9', okrId: 'okr-3', nome: 'Checkout Dropoff', definicao: 'Abandono no checkout', meta: 30, frequencia: 'diario', valorAtual: 35, semaforo: 'vermelho', fonte: 'GA4', evidencia: '', notes: '' },
  ];

  const incidents: Incident[] = [
    {
      id: 'incident-1',
      sectorId: 'sector-3',
      titulo: 'Checkout travando no mobile',
      descricao: 'Usuários reportando erro 500 ao finalizar compra no mobile',
      evidencia: 'Screenshot do erro anexado',
      causaRaiz: 'Bug no gateway de pagamento mobile',
      acaoCorretiva: 'Rollback para versão anterior e fix urgente',
      ownerId: 'owner-4',
      prazo: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      prioridade: 'urgent',
      status: 'doing',
      validacao: [
        { id: 'v1', text: 'Testar checkout mobile 3x', checked: false },
        { id: 'v2', text: 'Monitorar taxa de erro por 24h', checked: false },
        { id: 'v3', text: 'Validar com 5 compras reais', checked: false },
      ],
      createdAt: new Date().toISOString(),
    },
    {
      id: 'incident-2',
      sectorId: 'sector-2',
      titulo: 'CPA disparou acima de R$35',
      descricao: 'CPA subiu 40% nas últimas 48h sem motivo aparente',
      evidencia: 'Print do Ads Manager',
      causaRaiz: 'Fadiga de criativo principal',
      acaoCorretiva: 'Pausar criativo fatigado, subir 3 novos',
      ownerId: 'owner-3',
      prazo: new Date(Date.now() + 48 * 60 * 60 * 1000).toISOString().split('T')[0],
      prioridade: 'high',
      status: 'todo',
      validacao: [
        { id: 'v1', text: 'CPA abaixo de R$28 por 3 dias', checked: false },
        { id: 'v2', text: 'ROAS acima de 3.5', checked: false },
        { id: 'v3', text: 'CTR dos novos criativos >2%', checked: false },
      ],
      createdAt: new Date().toISOString(),
    },
  ];

  const experiments: Experiment[] = [
    {
      id: 'exp-1',
      titulo: 'Teste de urgência no checkout',
      hipotese: 'Adicionar timer de urgência aumenta conversão em 10%',
      variavel: 'Timer de 15min no checkout',
      ownerId: 'owner-4',
      metricaSucesso: 'Taxa de conversão checkout',
      resultado: '',
      decisao: 'pendente',
      evidencia: '',
      dataInicio: today,
      dataFim: '',
      status: 'doing',
    },
    {
      id: 'exp-2',
      titulo: 'Criativo UGC vs Estúdio',
      hipotese: 'Criativos UGC terão CTR 30% maior que estúdio',
      variavel: 'Tipo de criativo (UGC vs Profissional)',
      ownerId: 'owner-3',
      metricaSucesso: 'CTR e CPA',
      resultado: 'UGC teve CTR 25% maior',
      decisao: 'duplicar',
      evidencia: 'Print Ads Manager',
      dataInicio: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      dataFim: today,
      status: 'done',
    },
  ];

  const scoreEntries: ScoreEntry[] = [
    {
      id: 'score-1',
      date: today,
      receita: 8500,
      pedidos: 52,
      ticketMedio: 163.46,
      margemBruta: 42,
      gastoMidia: 1200,
      cpa: 23.08,
      semaforoGeral: 'amarelo',
      observacoes: 'Dia com queda no tráfego orgânico',
      evidenciaLinks: [],
    },
  ];

  const weeklyCanvas: WeeklyCanvas[] = [
    {
      id: 'canvas-1',
      weekStart: weekStart.toISOString().split('T')[0],
      weekEnd: weekEnd.toISOString().split('T')[0],
      metaDiaria: 10000,
      metaSemanal: 70000,
      metaMensal: 300000,
      ofertaAncora: 'Kit Premium com 40% off',
      ticketAlvo: 180,
      margemAlvo: 45,
      drivers: {
        'sector-1': 'Manter 5 ofertas ativas/dia',
        'sector-2': 'Escalar tráfego com CPA <R$25',
        'sector-3': 'Aumentar conversão para 2.5%',
        'sector-4': 'Recuperar 200 carrinhos/semana',
      },
      checklistSemanal: [
        { id: 'cs1', text: 'Review semanal dos números', checked: false },
        { id: 'cs2', text: 'Análise de criativos', checked: false },
        { id: 'cs3', text: 'Planejamento da próxima semana', checked: false },
      ],
      testesSemana: ['exp-1'],
      pedrasTop3: ['incident-1', 'incident-2'],
      decisoesCEO: [
        { decisao: 'Dobrar budget em criativos vencedores', aprovado: true, proximoPasso: 'Walistter escalar na segunda' },
        { decisao: 'Contratar freela para mais UGC', aprovado: false, proximoPasso: 'Reavaliar no fim do mês' },
        { decisao: 'Focar 100% em tráfego pago', aprovado: true, proximoPasso: 'Pausar orgânico temporariamente' },
      ],
      recompensaPenaSemana: 'Pizza para equipe se bater meta semanal',
    },
  ];

  return {
    owners,
    sectors,
    routineTasks,
    okrs,
    krs,
    incidents,
    experiments,
    scoreEntries,
    weeklyCanvas,
  };
};
