import type {
  Owner,
  Marketplace,
  RoutineTask,
  TaskTemplate,
  KPIEntry,
  Incident,
  Experiment,
  ScoreWeek,
  TaskStep,
} from '@/types';

const today = new Date().toISOString().split('T')[0];
const yesterday = new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString().split('T')[0];
const weekStart = new Date();
weekStart.setDate(weekStart.getDate() - weekStart.getDay());
const weekEnd = new Date(weekStart);
weekEnd.setDate(weekEnd.getDate() + 6);

// Helper para criar campos operacionais default
const createOperationalDefaults = (overrides?: {
  description?: string;
  steps?: TaskStep[];
  inputs?: string[];
  outputs?: string[];
  commonMistakes?: string[];
  timeboxMinutes?: number;
  toolsLinks?: { label: string; url: string }[];
  evidenceExamples?: string[];
  escalationRule?: string;
}) => ({
  description: overrides?.description || '',
  steps: overrides?.steps || [],
  inputs: overrides?.inputs || [],
  outputs: overrides?.outputs || [],
  commonMistakes: overrides?.commonMistakes || [],
  timeboxMinutes: overrides?.timeboxMinutes || 15,
  toolsLinks: overrides?.toolsLinks || [],
  evidenceExamples: overrides?.evidenceExamples || [],
  escalationRule: overrides?.escalationRule || 'Se não conseguir completar, escalonar para o gestor imediato.',
});

export const generateSeedData = () => {
  // ============= OWNERS =============
  const owners: Owner[] = [
    { id: 'owner-1', nome: 'Péricles', cargo: 'CEO', avatarColor: 'hsl(220, 70%, 50%)', schedule: 'ALL_DAYS' },
    { id: 'owner-2', nome: 'Stella', cargo: 'CFO', avatarColor: 'hsl(280, 65%, 60%)', schedule: 'WEEKDAYS' },
    { id: 'owner-3', nome: 'Walistter', cargo: 'CMO', avatarColor: 'hsl(142, 76%, 36%)', schedule: 'WEEKDAYS' },
    { id: 'owner-4', nome: 'Elisangela', cargo: 'Gestora Marketplaces/CRM', avatarColor: 'hsl(38, 92%, 50%)', schedule: 'WEEKDAYS' },
  ];

  // ============= MARKETPLACES =============
  const marketplaces: Marketplace[] = [
    {
      id: 'mp-shein',
      name: 'Shein',
      priority: 'P1',
      stage: 'SCALE',
      isSelling: true,
      cadence: 'DAILY',
      ownerId: 'owner-4',
      modulesEnabled: { crm: false, paidAds: false, supportSla: true, live: false, affiliates: false },
      cutoffTime: '14:00',
      notes: 'Canal líder. Foco em volume e reputação.',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'mp-shopee-150',
      name: 'Shopee 1:50',
      priority: 'P1',
      stage: 'SCALE',
      isSelling: true,
      cadence: 'DAILY',
      ownerId: 'owner-4',
      modulesEnabled: { crm: false, paidAds: true, supportSla: true, live: true, affiliates: true },
      cutoffTime: '15:00',
      notes: 'Alto GMV. Priorizar Lives e Ads Shopee.',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'mp-shopee-biju',
      name: 'Shopee Biju',
      priority: 'P2',
      stage: 'SCALE',
      isSelling: true,
      cadence: 'DAILY',
      ownerId: 'owner-4',
      modulesEnabled: { crm: false, paidAds: true, supportSla: true, live: false, affiliates: false },
      cutoffTime: '15:00',
      notes: 'Loja secundária. Manter saudável.',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'mp-amazon',
      name: 'Amazon',
      priority: 'P2',
      stage: 'SETUP',
      isSelling: false,
      cadence: 'SETUP_SPRINT',
      ownerId: 'owner-4',
      modulesEnabled: { crm: false, paidAds: false, supportSla: true, live: false, affiliates: false },
      cutoffTime: '16:00',
      notes: 'Em setup. Meta: 1ª venda em 15 dias.',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'mp-ml',
      name: 'Mercado Livre',
      priority: 'P2',
      stage: 'RECOVER',
      isSelling: true,
      cadence: 'RECOVER',
      ownerId: 'owner-4',
      modulesEnabled: { crm: false, paidAds: true, supportSla: true, live: false, affiliates: false },
      cutoffTime: '14:00',
      notes: 'Reputação caiu. Foco em SLA e atendimento.',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'mp-magalu',
      name: 'Magalu',
      priority: 'P3',
      stage: 'SCALE',
      isSelling: true,
      cadence: 'WEEKLY',
      ownerId: 'owner-4',
      modulesEnabled: { crm: false, paidAds: false, supportSla: true, live: false, affiliates: false },
      cutoffTime: '12:00',
      notes: 'Baixo volume. Manter mínimo.',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'mp-netshoes',
      name: 'Netshoes/Zattini',
      priority: 'P3',
      stage: 'PAUSED',
      isSelling: false,
      cadence: 'WEEKLY',
      ownerId: 'owner-4',
      modulesEnabled: { crm: false, paidAds: false, supportSla: false, live: false, affiliates: false },
      cutoffTime: '14:00',
      notes: 'Pausado. Reavaliar no Q2.',
      createdAt: new Date().toISOString(),
    },
  ];

  // ============= ROUTINE TASKS (P1 SCALE) =============
  const routineTasks: RoutineTask[] = [
    // Tarefas Globais (matinais) - CEO
    {
      id: 'task-global-1',
      marketplaceId: null,
      ownerId: 'owner-1',
      cadence: 'DAILY',
      time: '08:00',
      type: 'HIGIENE',
      title: 'Check Painel Geral (5 números ontem)',
      dod: 'Verificar GMV, pedidos, ticket, margem e SLA de todos canais',
      ...createOperationalDefaults({
        description: `## Objetivo
Garantir visibilidade diária dos principais indicadores de todos os canais.

## Por que é importante
O check matinal permite identificar problemas antes que se tornem críticos e direcionar o foco do dia.`,
        steps: [
          { id: 's1', text: 'Acessar o painel consolidado', completed: false },
          { id: 's2', text: 'Verificar GMV total vs meta', completed: false },
          { id: 's3', text: 'Verificar pedidos por canal', completed: false },
          { id: 's4', text: 'Verificar ticket médio', completed: false },
          { id: 's5', text: 'Verificar margem bruta', completed: false },
          { id: 's6', text: 'Verificar SLA de expedição', completed: false },
        ],
        inputs: ['Acesso ao painel de BI', 'Dados do dia anterior consolidados'],
        outputs: ['5 números registrados', 'Alertas identificados'],
        commonMistakes: ['Não verificar todos os canais', 'Ignorar variações pequenas que podem ser tendência'],
        timeboxMinutes: 15,
        toolsLinks: [{ label: 'Painel BI', url: 'https://bi.exemplo.com' }],
        evidenceExamples: ['Print do painel com os 5 números destacados', 'Anotação com os valores no sistema'],
        escalationRule: 'Se GMV < 70% da meta, escalonar imediatamente para reunião de crise.',
      }),
      evidenceRequired: true,
      critical: true,
      points: 3,
      status: 'TODO',
      evidenceLinks: [],
      completedAt: null,
      completedByOwnerId: null,
      skipReason: null,
      date: today,
      createdAt: new Date().toISOString(),
    },
    {
      id: 'task-global-2',
      marketplaceId: null,
      ownerId: 'owner-1',
      cadence: 'DAILY',
      time: '08:30',
      type: 'HIGIENE',
      title: 'Revisar Incidentes Abertos',
      dod: 'Checar status de todas as pedras e atualizar se necessário',
      ...createOperationalDefaults({
        description: 'Revisar todos os incidentes abertos para garantir que estão sendo tratados.',
        steps: [
          { id: 's1', text: 'Acessar página de Incidentes', completed: false },
          { id: 's2', text: 'Filtrar por OPEN e IN_PROGRESS', completed: false },
          { id: 's3', text: 'Verificar progresso de cada um', completed: false },
        ],
        timeboxMinutes: 10,
      }),
      evidenceRequired: false,
      critical: false,
      points: 1,
      status: 'TODO',
      evidenceLinks: [],
      completedAt: null,
      completedByOwnerId: null,
      skipReason: null,
      date: today,
      createdAt: new Date().toISOString(),
    },
    // Shein (P1) - Elisangela
    {
      id: 'task-shein-1',
      marketplaceId: 'mp-shein',
      ownerId: 'owner-4',
      cadence: 'DAILY',
      time: '09:00',
      type: 'HIGIENE',
      title: '[SHEIN] Responder mensagens pendentes',
      dod: 'Todas mensagens respondidas em <2h',
      ...createOperationalDefaults({
        description: `## Objetivo
Manter taxa de resposta acima de 95% e tempo médio abaixo de 2 horas.

## Contexto
A Shein penaliza lojas com tempo de resposta alto, afetando exposição e vendas.`,
        steps: [
          { id: 's1', text: 'Acessar Seller Center Shein', completed: false },
          { id: 's2', text: 'Ir em "Mensagens"', completed: false },
          { id: 's3', text: 'Responder todas mensagens pendentes', completed: false },
          { id: 's4', text: 'Verificar se há disputas abertas', completed: false },
        ],
        inputs: ['Acesso Seller Center Shein'],
        outputs: ['Mensagens zeradas', 'Print da caixa vazia'],
        commonMistakes: ['Responder de forma genérica', 'Não verificar disputas'],
        timeboxMinutes: 20,
        toolsLinks: [{ label: 'Seller Center Shein', url: 'https://seller.shein.com' }],
        evidenceExamples: ['Print mostrando 0 mensagens pendentes'],
        escalationRule: 'Se houver disputa complexa, escalonar para Péricles.',
      }),
      evidenceRequired: true,
      critical: true,
      points: 3,
      status: 'TODO',
      evidenceLinks: [],
      completedAt: null,
      completedByOwnerId: null,
      skipReason: null,
      date: today,
      createdAt: new Date().toISOString(),
    },
    {
      id: 'task-shein-2',
      marketplaceId: 'mp-shein',
      ownerId: 'owner-4',
      cadence: 'DAILY',
      time: '10:00',
      type: 'PROTECAO',
      title: '[SHEIN] Checar reputação e reclamações',
      dod: 'Score acima de 4.7, sem reclamações pendentes',
      ...createOperationalDefaults({
        description: 'Monitorar score e resolver reclamações antes que afetem reputação.',
        timeboxMinutes: 15,
      }),
      evidenceRequired: true,
      critical: true,
      points: 3,
      status: 'TODO',
      evidenceLinks: [],
      completedAt: null,
      completedByOwnerId: null,
      skipReason: null,
      date: today,
      createdAt: new Date().toISOString(),
    },
    {
      id: 'task-shein-3',
      marketplaceId: 'mp-shein',
      ownerId: 'owner-4',
      cadence: 'DAILY',
      time: '11:00',
      type: 'CRESCIMENTO',
      title: '[SHEIN] Subir 5 novos produtos ou atualizar preços',
      dod: '5 SKUs atualizados com preço competitivo',
      ...createOperationalDefaults({ timeboxMinutes: 30 }),
      evidenceRequired: true,
      critical: false,
      points: 1,
      status: 'TODO',
      evidenceLinks: [],
      completedAt: null,
      completedByOwnerId: null,
      skipReason: null,
      date: today,
      createdAt: new Date().toISOString(),
    },
    {
      id: 'task-shein-4',
      marketplaceId: 'mp-shein',
      ownerId: 'owner-4',
      cadence: 'DAILY',
      time: '14:00',
      type: 'HIGIENE',
      title: '[SHEIN] Expedição até cutoff (14h)',
      dod: 'Todos pedidos do dia expedidos',
      ...createOperationalDefaults({
        description: 'Expedir todos os pedidos antes do cutoff para manter SLA.',
        steps: [
          { id: 's1', text: 'Imprimir etiquetas pendentes', completed: false },
          { id: 's2', text: 'Separar produtos', completed: false },
          { id: 's3', text: 'Embalar e etiquetar', completed: false },
          { id: 's4', text: 'Postar/agendar coleta', completed: false },
        ],
        timeboxMinutes: 60,
        escalationRule: 'Se não conseguir expedir todos, avisar Péricles antes do cutoff.',
      }),
      evidenceRequired: true,
      critical: true,
      points: 3,
      status: 'TODO',
      evidenceLinks: [],
      completedAt: null,
      completedByOwnerId: null,
      skipReason: null,
      date: today,
      createdAt: new Date().toISOString(),
    },
    // Shopee 1:50 (P1) - Elisangela
    {
      id: 'task-shopee150-1',
      marketplaceId: 'mp-shopee-150',
      ownerId: 'owner-4',
      cadence: 'DAILY',
      time: '09:00',
      type: 'HIGIENE',
      title: '[SHOPEE 1:50] Responder chat pendente',
      dod: 'Taxa de resposta >95%, tempo <30min',
      ...createOperationalDefaults({ timeboxMinutes: 20 }),
      evidenceRequired: true,
      critical: true,
      points: 3,
      status: 'TODO',
      evidenceLinks: [],
      completedAt: null,
      completedByOwnerId: null,
      skipReason: null,
      date: today,
      createdAt: new Date().toISOString(),
    },
    {
      id: 'task-shopee150-2',
      marketplaceId: 'mp-shopee-150',
      ownerId: 'owner-4',
      cadence: 'DAILY',
      time: '10:30',
      type: 'CRESCIMENTO',
      title: '[SHOPEE 1:50] Configurar promoção do dia',
      dod: 'Pelo menos 1 promoção ativa com desconto atrativo',
      ...createOperationalDefaults({ timeboxMinutes: 15 }),
      evidenceRequired: true,
      critical: false,
      points: 1,
      status: 'TODO',
      evidenceLinks: [],
      completedAt: null,
      completedByOwnerId: null,
      skipReason: null,
      date: today,
      createdAt: new Date().toISOString(),
    },
    {
      id: 'task-shopee150-3',
      marketplaceId: 'mp-shopee-150',
      ownerId: 'owner-3',
      cadence: 'DAILY',
      time: '12:00',
      type: 'CRESCIMENTO',
      title: '[SHOPEE 1:50] Verificar Ads e ajustar lances',
      dod: 'ROAS >3x, pausar anúncios com CPA alto',
      ...createOperationalDefaults({ timeboxMinutes: 20 }),
      evidenceRequired: true,
      critical: false,
      points: 1,
      status: 'TODO',
      evidenceLinks: [],
      completedAt: null,
      completedByOwnerId: null,
      skipReason: null,
      date: today,
      createdAt: new Date().toISOString(),
    },
    {
      id: 'task-shopee150-4',
      marketplaceId: 'mp-shopee-150',
      ownerId: 'owner-4',
      cadence: 'DAILY',
      time: '15:00',
      type: 'HIGIENE',
      title: '[SHOPEE 1:50] Expedição até cutoff (15h)',
      dod: 'Todos pedidos expedidos no prazo',
      ...createOperationalDefaults({ timeboxMinutes: 60 }),
      evidenceRequired: true,
      critical: true,
      points: 3,
      status: 'TODO',
      evidenceLinks: [],
      completedAt: null,
      completedByOwnerId: null,
      skipReason: null,
      date: today,
      createdAt: new Date().toISOString(),
    },
    // ML RECOVER - Elisangela
    {
      id: 'task-ml-recover-1',
      marketplaceId: 'mp-ml',
      ownerId: 'owner-4',
      cadence: 'RECOVER',
      time: '09:00',
      type: 'PROTECAO',
      title: '[ML RECOVER] Responder TODAS reclamações',
      dod: 'Zero reclamações pendentes',
      ...createOperationalDefaults({ timeboxMinutes: 30 }),
      evidenceRequired: true,
      critical: true,
      points: 3,
      status: 'TODO',
      evidenceLinks: [],
      completedAt: null,
      completedByOwnerId: null,
      skipReason: null,
      date: today,
      createdAt: new Date().toISOString(),
    },
    {
      id: 'task-ml-recover-2',
      marketplaceId: 'mp-ml',
      ownerId: 'owner-4',
      cadence: 'RECOVER',
      time: '10:00',
      type: 'PROTECAO',
      title: '[ML RECOVER] Auditar SLA expedição',
      dod: 'SLA >98%, zero atrasos',
      ...createOperationalDefaults({ timeboxMinutes: 20 }),
      evidenceRequired: true,
      critical: true,
      points: 3,
      status: 'TODO',
      evidenceLinks: [],
      completedAt: null,
      completedByOwnerId: null,
      skipReason: null,
      date: today,
      createdAt: new Date().toISOString(),
    },
    {
      id: 'task-ml-recover-3',
      marketplaceId: 'mp-ml',
      ownerId: 'owner-4',
      cadence: 'RECOVER',
      time: '11:00',
      type: 'PROTECAO',
      title: '[ML RECOVER] Resolver devoluções pendentes',
      dod: 'Todas devoluções processadas',
      ...createOperationalDefaults({ timeboxMinutes: 30 }),
      evidenceRequired: true,
      critical: true,
      points: 3,
      status: 'TODO',
      evidenceLinks: [],
      completedAt: null,
      completedByOwnerId: null,
      skipReason: null,
      date: today,
      createdAt: new Date().toISOString(),
    },
    {
      id: 'task-ml-recover-4',
      marketplaceId: 'mp-ml',
      ownerId: 'owner-4',
      cadence: 'RECOVER',
      time: '14:00',
      type: 'PROTECAO',
      title: '[ML RECOVER] Expedição prioritária',
      dod: 'Expedir antes do cutoff com rastreio atualizado',
      ...createOperationalDefaults({ timeboxMinutes: 60 }),
      evidenceRequired: true,
      critical: true,
      points: 3,
      status: 'TODO',
      evidenceLinks: [],
      completedAt: null,
      completedByOwnerId: null,
      skipReason: null,
      date: today,
      createdAt: new Date().toISOString(),
    },
    // Amazon SETUP - Elisangela
    {
      id: 'task-amazon-setup-1',
      marketplaceId: 'mp-amazon',
      ownerId: 'owner-4',
      cadence: 'SETUP_SPRINT',
      time: '09:00',
      type: 'SETUP',
      title: '[AMAZON SETUP] Cadastrar 10 SKUs hoje',
      dod: '10 produtos ativos com fotos e descrição',
      ...createOperationalDefaults({ timeboxMinutes: 60 }),
      evidenceRequired: true,
      critical: true,
      points: 3,
      status: 'TODO',
      evidenceLinks: [],
      completedAt: null,
      completedByOwnerId: null,
      skipReason: null,
      date: today,
      createdAt: new Date().toISOString(),
    },
    {
      id: 'task-amazon-setup-2',
      marketplaceId: 'mp-amazon',
      ownerId: 'owner-4',
      cadence: 'SETUP_SPRINT',
      time: '11:00',
      type: 'SETUP',
      title: '[AMAZON SETUP] Testar checkout (compra simulada)',
      dod: 'Checkout funcionando, frete calculado corretamente',
      ...createOperationalDefaults({ timeboxMinutes: 20 }),
      evidenceRequired: true,
      critical: true,
      points: 3,
      status: 'TODO',
      evidenceLinks: [],
      completedAt: null,
      completedByOwnerId: null,
      skipReason: null,
      date: today,
      createdAt: new Date().toISOString(),
    },
    {
      id: 'task-amazon-setup-3',
      marketplaceId: 'mp-amazon',
      ownerId: 'owner-4',
      cadence: 'SETUP_SPRINT',
      time: '14:00',
      type: 'SETUP',
      title: '[AMAZON SETUP] Revisar precificação vs concorrência',
      dod: 'Preços competitivos em relação aos 3 principais concorrentes',
      ...createOperationalDefaults({ timeboxMinutes: 30 }),
      evidenceRequired: true,
      critical: false,
      points: 1,
      status: 'TODO',
      evidenceLinks: [],
      completedAt: null,
      completedByOwnerId: null,
      skipReason: null,
      date: today,
      createdAt: new Date().toISOString(),
    },
    // Tarefa de fechamento - CEO
    {
      id: 'task-global-close',
      marketplaceId: null,
      ownerId: 'owner-1',
      cadence: 'DAILY',
      time: '18:00',
      type: 'HIGIENE',
      title: 'Fechamento do Dia (Painel 5 números)',
      dod: 'Preencher GMV, pedidos, ticket, margem e observações do dia',
      ...createOperationalDefaults({
        description: 'Consolidar números do dia e registrar observações importantes.',
        timeboxMinutes: 20,
      }),
      evidenceRequired: true,
      critical: true,
      points: 3,
      status: 'TODO',
      evidenceLinks: [],
      completedAt: null,
      completedByOwnerId: null,
      skipReason: null,
      date: today,
      createdAt: new Date().toISOString(),
    },
    // Tarefa CFO - Stella
    {
      id: 'task-cfo-1',
      marketplaceId: null,
      ownerId: 'owner-2',
      cadence: 'DAILY',
      time: '10:00',
      type: 'HIGIENE',
      title: 'Conferir fluxo de caixa do dia anterior',
      dod: 'Conciliação bancária ok, sem divergências',
      ...createOperationalDefaults({ timeboxMinutes: 30 }),
      evidenceRequired: true,
      critical: false,
      points: 1,
      status: 'TODO',
      evidenceLinks: [],
      completedAt: null,
      completedByOwnerId: null,
      skipReason: null,
      date: today,
      createdAt: new Date().toISOString(),
    },
    // Tarefa CMO - Walistter
    {
      id: 'task-cmo-1',
      marketplaceId: null,
      ownerId: 'owner-3',
      cadence: 'DAILY',
      time: '09:30',
      type: 'CRESCIMENTO',
      title: 'Revisar performance de campanhas (todos canais)',
      dod: 'Dashboard atualizado, ajustes feitos se necessário',
      ...createOperationalDefaults({ timeboxMinutes: 30 }),
      evidenceRequired: true,
      critical: false,
      points: 1,
      status: 'TODO',
      evidenceLinks: [],
      completedAt: null,
      completedByOwnerId: null,
      skipReason: null,
      date: today,
      createdAt: new Date().toISOString(),
    },
  ];

  // ============= KPI ENTRIES =============
  const kpiEntries: KPIEntry[] = [
    // KPIs de HOJE (para que o Dashboard não fique vazio)
    {
      id: 'kpi-shein-today',
      date: today,
      marketplaceId: 'mp-shein',
      stageSnapshot: 'SCALE',
      values: {
        gmv: 2950,
        pedidos: 42,
        ticketMedio: 70.24,
        sessoes: 1150,
        conversao: 3.65,
        itensVendidos: 88,
        reputacao: 4.8,
        slaExpedicao: 98,
      },
      semaforo: 'GREEN',
      notes: 'Dia em andamento. Projeção boa.',
      evidenceLinks: [],
    },
    {
      id: 'kpi-shopee150-today',
      date: today,
      marketplaceId: 'mp-shopee-150',
      stageSnapshot: 'SCALE',
      values: {
        gmv: 2650,
        pedidos: 35,
        ticketMedio: 75.71,
        sessoes: 920,
        conversao: 3.80,
        itensVendidos: 70,
        reputacao: 4.9,
        slaExpedicao: 100,
      },
      semaforo: 'GREEN',
      notes: 'Campanha de cupom ativa.',
      evidenceLinks: [],
    },
    {
      id: 'kpi-ml-today',
      date: today,
      marketplaceId: 'mp-ml',
      stageSnapshot: 'RECOVER',
      values: {
        gmv: 980,
        pedidos: 15,
        ticketMedio: 65.33,
        sessoes: 520,
        conversao: 2.88,
        itensVendidos: 24,
        reputacao: 4.35,
        slaExpedicao: 94,
      },
      semaforo: 'YELLOW',
      notes: 'Reputação subindo lentamente. SLA melhorou.',
      evidenceLinks: [],
    },
    // KPIs de ONTEM
    {
      id: 'kpi-shein-1',
      date: yesterday,
      marketplaceId: 'mp-shein',
      stageSnapshot: 'SCALE',
      values: {
        gmv: 3200,
        pedidos: 45,
        ticketMedio: 71.11,
        sessoes: 1200,
        conversao: 3.75,
        itensVendidos: 92,
        reputacao: 4.8,
        slaExpedicao: 99,
      },
      semaforo: 'GREEN',
      notes: 'Dia forte. Promoção relâmpago funcionou.',
      evidenceLinks: [],
    },
    {
      id: 'kpi-shopee150-1',
      date: yesterday,
      marketplaceId: 'mp-shopee-150',
      stageSnapshot: 'SCALE',
      values: {
        gmv: 2800,
        pedidos: 38,
        ticketMedio: 73.68,
        sessoes: 980,
        conversao: 3.88,
        itensVendidos: 76,
        reputacao: 4.9,
        slaExpedicao: 100,
      },
      semaforo: 'GREEN',
      notes: 'Live performou bem. Considerar aumentar frequência.',
      evidenceLinks: [],
    },
    {
      id: 'kpi-shopeebiju-1',
      date: yesterday,
      marketplaceId: 'mp-shopee-biju',
      stageSnapshot: 'SCALE',
      values: {
        gmv: 850,
        pedidos: 22,
        ticketMedio: 38.64,
        sessoes: 450,
        conversao: 4.89,
        itensVendidos: 44,
        reputacao: 4.7,
        slaExpedicao: 98,
      },
      semaforo: 'YELLOW',
      notes: 'GMV abaixo da média. Revisar mix.',
      evidenceLinks: [],
    },
    {
      id: 'kpi-ml-1',
      date: yesterday,
      marketplaceId: 'mp-ml',
      stageSnapshot: 'RECOVER',
      values: {
        gmv: 1200,
        pedidos: 18,
        ticketMedio: 66.67,
        sessoes: 600,
        conversao: 3.0,
        itensVendidos: 28,
        reputacao: 4.3,
        slaExpedicao: 92,
      },
      semaforo: 'RED',
      notes: 'Reputação crítica. SLA precisa melhorar urgente.',
      evidenceLinks: [],
    },
    {
      id: 'kpi-magalu-1',
      date: yesterday,
      marketplaceId: 'mp-magalu',
      stageSnapshot: 'SCALE',
      values: {
        gmv: 420,
        pedidos: 8,
        ticketMedio: 52.50,
        sessoes: 180,
        conversao: 4.44,
        itensVendidos: 12,
        reputacao: 4.6,
        slaExpedicao: 100,
      },
      semaforo: 'GREEN',
      notes: 'Baixo volume mas saudável.',
      evidenceLinks: [],
    },
  ];

  // ============= INCIDENTS =============
  const incidents: Incident[] = [
    {
      id: 'inc-1',
      marketplaceId: 'mp-ml',
      createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      severity: 'HIGH',
      title: 'Reputação ML caiu para 4.3',
      description: 'Score de reputação caiu abaixo do mínimo aceitável (4.5)',
      triggerRule: 'reputacao < 4.5',
      ownerId: 'owner-4',
      status: 'IN_PROGRESS',
      rootCause: 'Atrasos na expedição por problemas com transportadora',
      correctiveAction: 'Priorizar expedição ML. Trocar transportadora para Full.',
      preventiveAction: 'Implementar alerta automático de SLA.',
      validationEvidenceLinks: [],
      dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      tags: ['reputation', 'sla'],
    },
    {
      id: 'inc-2',
      marketplaceId: 'mp-shopee-biju',
      createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      severity: 'MED',
      title: 'GMV Shopee Biju -40% vs média',
      description: 'Queda significativa no GMV comparado à média dos últimos 7 dias',
      triggerRule: 'gmv < media7d * 0.6',
      ownerId: 'owner-4',
      status: 'OPEN',
      rootCause: '',
      correctiveAction: '',
      preventiveAction: '',
      validationEvidenceLinks: [],
      dueDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      tags: ['other'],
    },
    {
      id: 'inc-3',
      marketplaceId: null,
      createdAt: new Date().toISOString(),
      severity: 'CRITICAL',
      title: 'Ruptura SKU campeão (Kit Premium)',
      description: 'SKU mais vendido sem estoque há 2 dias',
      triggerRule: 'estoque_sku_campeao = 0',
      ownerId: 'owner-1',
      status: 'OPEN',
      rootCause: 'Fornecedor atrasou entrega',
      correctiveAction: 'Contatar fornecedor alternativo',
      preventiveAction: 'Aumentar estoque mínimo de SKUs campeões',
      validationEvidenceLinks: [],
      dueDate: today,
      tags: ['rupture'],
    },
  ];

  // ============= EXPERIMENTS =============
  const experiments: Experiment[] = [
    {
      id: 'exp-1',
      marketplaceId: 'mp-shopee-150',
      hypothesis: 'Lives com ofertas exclusivas aumentam GMV em 30%',
      variable: 'Oferta exclusiva na Live vs oferta normal',
      metric: 'GMV durante Live',
      successCriteria: 'GMV 30% maior que Lives sem oferta exclusiva',
      startDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      endDate: null,
      status: 'RUNNING',
      resultNotes: '',
      evidenceLinks: [],
      decision: null,
      ownerId: 'owner-4',
    },
    {
      id: 'exp-2',
      marketplaceId: 'mp-shein',
      hypothesis: 'Fotos com modelo real aumentam conversão em 20%',
      variable: 'Foto com modelo vs foto still',
      metric: 'Taxa de conversão',
      successCriteria: 'Conversão 20% maior nos produtos com modelo',
      startDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      endDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      status: 'WON',
      resultNotes: 'Conversão 25% maior. Duplicar para todos os top 50 SKUs.',
      evidenceLinks: ['Print comparativo de conversão'],
      decision: 'DUPLICAR',
      ownerId: 'owner-4',
    },
    {
      id: 'exp-3',
      marketplaceId: 'mp-shopee-150',
      hypothesis: 'Frete grátis acima de R$50 aumenta ticket médio',
      variable: 'Threshold de frete grátis (R$50 vs R$79)',
      metric: 'Ticket médio e margem',
      successCriteria: 'Ticket médio +15% sem perda de margem',
      startDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      endDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      status: 'LOST',
      resultNotes: 'Ticket aumentou 8% mas margem caiu 12%. Não compensa.',
      evidenceLinks: [],
      decision: 'MATAR',
      ownerId: 'owner-4',
    },
  ];

  // ============= SCORE WEEKS =============
  const scoreWeeks: ScoreWeek[] = [
    {
      id: 'score-week-1',
      weekStartDate: weekStart.toISOString().split('T')[0],
      weekEndDate: weekEnd.toISOString().split('T')[0],
      ownerScores: [
        { ownerId: 'owner-1', points: 45, tasksCompleted: 12, tasksMissed: 2, criticalCompleted: 6, criticalMissed: 1 },
        { ownerId: 'owner-4', points: 82, tasksCompleted: 28, tasksMissed: 4, criticalCompleted: 14, criticalMissed: 2 },
      ],
      marketplaceScores: [
        { marketplaceId: 'mp-shein', points: 35, tasksCompleted: 12, gmvTotal: 18500, incidentsOpen: 0 },
        { marketplaceId: 'mp-shopee-150', points: 32, tasksCompleted: 11, gmvTotal: 16200, incidentsOpen: 0 },
        { marketplaceId: 'mp-ml', points: 18, tasksCompleted: 8, gmvTotal: 7800, incidentsOpen: 1 },
      ],
      penaltiesRewardsNotes: 'Elisangela: +10 bônus por resolver incidente ML em <24h',
      finalDecision: 'Foco da próxima semana: recuperar ML e acelerar Amazon setup',
    },
  ];

  // ============= TASK TEMPLATES =============
  const taskTemplates: TaskTemplate[] = [
    {
      id: 'template-global-morning',
      marketplaceId: null,
      ownerId: 'owner-1',
      time: '08:00',
      type: 'HIGIENE',
      title: 'Check Painel Geral (5 números ontem)',
      dod: 'Verificar GMV, pedidos, ticket, margem e SLA de todos canais',
      ...createOperationalDefaults({
        description: `## Objetivo
Garantir visibilidade diária dos principais indicadores de todos os canais.`,
        steps: [
          { id: 's1', text: 'Acessar o painel consolidado', completed: false },
          { id: 's2', text: 'Verificar GMV total vs meta', completed: false },
          { id: 's3', text: 'Verificar pedidos por canal', completed: false },
          { id: 's4', text: 'Verificar ticket médio', completed: false },
          { id: 's5', text: 'Verificar margem bruta', completed: false },
          { id: 's6', text: 'Verificar SLA de expedição', completed: false },
        ],
        timeboxMinutes: 15,
      }),
      evidenceRequired: true,
      critical: true,
      points: 3,
      weekDays: ['seg', 'ter', 'qua', 'qui', 'sex'],
      isActive: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: 'template-shein-messages',
      marketplaceId: 'mp-shein',
      ownerId: 'owner-4',
      time: '09:00',
      type: 'HIGIENE',
      title: '[SHEIN] Responder mensagens pendentes',
      dod: 'Todas mensagens respondidas em <2h',
      ...createOperationalDefaults({ timeboxMinutes: 20 }),
      evidenceRequired: true,
      critical: true,
      points: 3,
      weekDays: ['seg', 'ter', 'qua', 'qui', 'sex'],
      isActive: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: 'template-shopee-chat',
      marketplaceId: 'mp-shopee-150',
      ownerId: 'owner-4',
      time: '09:00',
      type: 'HIGIENE',
      title: '[SHOPEE 1:50] Responder chat pendente',
      dod: 'Taxa de resposta >95%, tempo <30min',
      ...createOperationalDefaults({ timeboxMinutes: 20 }),
      evidenceRequired: true,
      critical: true,
      points: 3,
      weekDays: ['seg', 'ter', 'qua', 'qui', 'sex'],
      isActive: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: 'template-global-close',
      marketplaceId: null,
      ownerId: 'owner-1',
      time: '18:00',
      type: 'HIGIENE',
      title: 'Fechamento do Dia (Painel 5 números)',
      dod: 'Preencher GMV, pedidos, ticket, margem e observações do dia',
      ...createOperationalDefaults({ timeboxMinutes: 20 }),
      evidenceRequired: true,
      critical: true,
      points: 3,
      weekDays: ['seg', 'ter', 'qua', 'qui', 'sex'],
      isActive: true,
      createdAt: new Date().toISOString(),
    },
  ];

  // ============= PRODUCTS (Campeões Pareto) =============
  const products = [
    { id: 'prod-1', sku: '6006-Branco-GLisa-VivoBran', name: 'Macacão Branco G Lisa Vivo Branco RN/P', isChampion: true, typeStrategy: 'SINGLE_HERO' as const, marketplacesSelling: ['mp-shein', 'mp-shopee-150'], notes: 'Campeão de vendas', createdAt: new Date().toISOString() },
    { id: 'prod-2', sku: '1006-Branco-Rococo', name: 'Saída Maternidade Rococó Branco RN/P', isChampion: true, typeStrategy: 'SINGLE_HERO' as const, marketplacesSelling: ['mp-shein', 'mp-shopee-150'], notes: '', createdAt: new Date().toISOString() },
    { id: 'prod-3', sku: '1004-PicuetaLisa', name: 'Saída Maternidade Picueta Lisa RN/P', isChampion: true, typeStrategy: 'SINGLE_HERO' as const, marketplacesSelling: ['mp-shopee-150'], notes: '', createdAt: new Date().toISOString() },
    { id: 'prod-4', sku: '4001-Trigal-Branco', name: 'Kit Trigal Branco RN/P', isChampion: true, typeStrategy: 'KIT_HERO' as const, marketplacesSelling: [], notes: 'Kit para loja própria', createdAt: new Date().toISOString() },
    { id: 'prod-5', sku: '4001-Trigal-Azul', name: 'Kit Trigal Azul RN/P', isChampion: true, typeStrategy: 'KIT_HERO' as const, marketplacesSelling: [], notes: 'Kit para loja própria', createdAt: new Date().toISOString() },
    { id: 'prod-6', sku: '4001-Trigal-Capuccino', name: 'Kit Trigal Capuccino RN/P', isChampion: true, typeStrategy: 'KIT_HERO' as const, marketplacesSelling: [], notes: '', createdAt: new Date().toISOString() },
  ];

  return {
    owners,
    marketplaces,
    products,
    routineTasks,
    taskTemplates,
    kpiEntries,
    incidents,
    experiments,
    scoreWeeks,
  };
};
